testing: false

# Site settings
title: "Mathematical Theory of Probability (Rutgers 01:640:477, section 05,
Spring 2019)"
page_title: "Mathematical Theory of Probability"
course_title: "Rutgers MATH 477, Spring 2019."
description: ""
instructor: "Daniel Krashen"
email: "daniel.krashen+prob@gmail.com"
office: "Hill Center 220 (Busch Campus)"
office_hours: "After class on Tuesdays, 1:25--2:25, Business Rockefeller Road, room 1071"
TA_office_hours: "In person Mon 11-12 and Fri 2-3 in Hill 101; 
Online Wed 2-3"
lecture_schedule: "Tues/Fri 12:00pm-1:20pm, Business Rockafeller Road 1071
(Livingston Campus)"

baseurl: "/probability"
url: "http://dkrashen.github.io"

# url: "localhost:4000"
# url: "http://math.dkrashen.org"

# Build settings
markdown: kramdown
permalink: pretty
